# Generated by Django 2.2.6 on 2019-10-05 09:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20191005_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonzai',
            name='img_arbre',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/logo/'), upload_to=''),
        ),
    ]
