# Generated by Django 2.2.6 on 2019-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20191005_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonzai',
            name='img_arbre',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
