# Generated by Django 2.2.6 on 2019-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_auto_20191005_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Arbre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Indefini', max_length=15)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
