# Generated by Django 2.2.6 on 2019-11-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20191115_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonzai',
            name='type_feuille',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APP.TypeFeuille'),
            preserve_default=False,
        ),
    ]
